### ISSUE TITLE
参考文献@incollection这种无法编译出书名

### ISSUE THREAD

**Issue by serenzhiyan** [sierxue/ThesisSWUFE#1]
参考文献的bibtex格式如下：
@incollection{yang_inventory_2005,
location = {London},
title = {Inventory Models of the Arrow-Harris-Marschak Type with Time Lag},
isbn = {978-1-137-02437-4 978-1-137-02438-1},
url = {http://link.springer.com/10.1057/9781137024381_4},
pages = {29--52},
booktitle = {{Herbert Scarf’s Contributions to Economics, Game Theory and Operations Research}},
publisher = {Palgrave Macmillan {UK}},
author = {Karlin, Samuel and Scarf, Herbert},
editor = {Yang, Zaifu},
urldate = {2020-05-07},
year = {2005},
langid = {english},
doi = {10.1057/9781137024381_4},
}
编译后的结果为：

![Screenshot from 2020-05-08 10-38-34](https://user-images.githubusercontent.com/50653708/81364448-402aa280-9118-11ea-8dac-0254958c54cf.png)

**Comment by sierxue** [comment]
编译后的结果由 `thesis-swufe.bst` 里的函数
```
FUNCTION {incollection}
{
    book
}
```
确定。可以看到，是按书的格式来显示的。
你可以参考 article 和 book 函数，修改 incollection 函数。

**Comment by serenzhiyan** [comment]
将@incollection{}里面的location项修改为address后，可以按照@book{}的格式编译了。
![Screenshot from 2020-05-11 17-24-02](https://user-images.githubusercontent.com/50653708/81545959-4173fd80-93ac-11ea-8470-396b77bc29fd.png)
