### ISSUE TITLE
编译时封面（Cover）超出页面范围而报错

### ISSUE THREAD

**Issue by Lasconnikov** [sierxue/ThesisSWUFE#2]
! Extra }, or forgotten \endgroup.
\UL@stop ...alty \ifnum \lastkern =\thr@@ \egroup
                                                  \egroup \ifdim \wd \UL@box...
l.16 \makecover

?
! Extra }, or forgotten \endgroup.
\UL@stop ...num \lastkern =\thr@@ \egroup \egroup
                                                  \ifdim \wd \UL@box =\z@ \e...
l.16 \makecover

**Comment by sierxue** [comment]
用 `latexmk example-multifile.tex` 编译试试看？

**Comment by Lasconnikov** [comment]
Overfull \hbox (19.25838pt too wide) in paragraph at lines 16--16
 [][]
[1] [2]
! Extra }, or forgotten \endgroup.
\UL@stop ...alty \ifnum \lastkern =\thr@@ \egroup
                                                  \egroup \ifdim \wd \UL@box...
l.16 \makecover

?
用这个指令 提示的是这个 
当我把 '\makecover'这个指令删除后编译可以成功运行出来结果
所以是不是这个封面的源代码不合适了？

**Comment by Lasconnikov** [comment]
当我在引用文献的时候，想使用（作者+年份）这种经济学引用形式  
使用这个命令\citep{wang1999sanwei}会出现以下错误：
) (./chapter/c2.tex [1]
Chapter 第二章.
! Undefined control sequence.
l.5 ...：“共同富裕是社会主义的本质要求，是人民群众的共同期盼。我们推动经济社会发\citet{wang1999sanwei}

**Comment by sierxue** [comment]
> Overfull \hbox (19.25838pt too wide) in paragraph at lines 16--16 [][] [1] [2] ! Extra }, or forgotten \endgroup. \UL@stop ...alty \ifnum \lastkern =\thr@@ \egroup \egroup \ifdim \wd \UL@box... l.16 \makecover
> 
> ? 用这个指令 提示的是这个 当我把 '\makecover'这个指令删除后编译可以成功运行出来结果 所以是不是这个封面的源代码不合适了？

在我的配置下，封面是可以编译的。我的系统是 ubuntu 20.04, texlive 2021. 我不清楚你的配置是什么。

另外，从你的报错信息，似乎你的 latex code 有错误，你再仔细检查一下。

也可以不使用 cover. 即在学校的 MS word 模板填写自己的信息后，转化成 pdf 文档，然后通过下面的命令和正文结合在一起。该命令需要的宏包我放在 cls 文件里了。

```
% \makecover
\includepdf[pages={1-6}]{frontcover.pdf}
```

**Comment by sierxue** [comment]
> 当我在引用文献的时候，想使用（作者+年份）这种经济学引用形式 使用这个命令\citep{wang1999sanwei}会出现以下错误： ) (./chapter/c2.tex [1] Chapter 第二章. ! Undefined control sequence. l.5 ...：“共同富裕是社会主义的本质要求，是人民群众的共同期盼。我们推动经济社会发\citet{wang1999sanwei}

这个问题你要在新的 issue 里提出，麻烦你移到一个新的 issue 里。
