### ISSUE TITLE
关于参考文献的引用格式问题

### ISSUE THREAD

**Issue by Lasconnikov** [sierxue/ThesisSWUFE#3]
我们在经济学文献引用的时候常常用这种格式：“……（林毅夫，2021）”或者 “……林毅夫（2021）在XXX指出……”。在模板的引用文献的过程中只能实现角标小数字的 引用格式，请问要在本模板中使用上述引用格式是否能实现？
提前谢谢大佬！

**Comment by sierxue** [comment]
学校的规范中可以使用 author year 这种引文方式吗？

**Comment by Lasconnikov** [comment]
学校问的文件格式word里面没有具体要求，不过我是看往年学长学姐的毕业论文使用这种方式，所以就问一下，如果实在不行的话，就是有手动打成（author year）这种格式了。其实后者也花不了很多时间，就是有轻微强迫症

**Comment by sierxue** [comment]
你可以在 https://github.com/x-magus/ThesisUESTC 的issue里提出这个问题。

如果得不到解决的化，有一个解决方案是使用其它的包，比如 natbib.

**Comment by Lasconnikov** [comment]
好的，谢谢
