### ISSUE TITLE
关于页眉的问题

### ISSUE THREAD

**Issue by Lasconnikov** [sierxue/ThesisSWUFE#4]
我看到研究生官网上的 硕士论文要求 是这样的，其中有关于页眉的问题，要实现奇偶页不同，还有就是一些行间距的要求，我发现模板的页眉没有实现奇偶页不同排。 我把研究生要求附在下面：

（1）纸张：论文用纸一律为A4纸张。
（2）正文板式（含版心设置）：正文字体为宋体，字号为小4号，每页30行、33列，行距用多倍行距1.37；版心设置为:上3.9CM，下3.4CM，左3.45CM，右3.45CM，页眉2.8CM，页脚2.5CM，书眉奇偶页不同。
(3)标题格式：一级标题用2号小标宋，二级标题用小3号黑体，三级标题用小4号黑体。
（4）图表字号5号，表题黑体，内容宋体；图表上下各空0.5行；表注用小5号宋体。
（5）页眉、页脚用宋体小5号。

冒昧问一下，请问您当时制作模板是按照这个要写设置格式的么？

**Comment by Lasconnikov** [comment]
页眉 页脚分布有规律 我看了图书馆打印出来的论文册，上面的规律是：奇数页则页眉页脚靠右侧，偶数页页眉页脚靠左侧。不是全部居中

**Comment by sierxue** [comment]
有两届硕士研究生使用这个模板，都通过了。我猜想学校并没有完全严格地按照这个标准执行。

**Comment by Lasconnikov** [comment]
这个问题我解决了，在cls文件里面使用奇数或者偶数项控制页眉和页码。
