### ISSUE TITLE
Hi, how to contact you, bro.

### ISSUE THREAD

**Issue by liaodalin19903** [sierxue/ThesisSWUFE#6]
do you have a email?

**Comment by ddpom** [comment]
My email is ***@***.***
 
From: markliao
Date: 2022-01-19 16:09
To: sierxue/ThesisSWUFE
CC: Subscribed
Subject: [sierxue/ThesisSWUFE] Hi, how to contact you, bro. (Issue #6)
do you have a email?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
