### ISSUE TITLE
\makecover报错

### ISSUE THREAD

**Issue by yifu-wang-201603** [sierxue/ThesisSWUFE#8]
谢谢项目创建者和各位校友的贡献！使用TexStudio编译过程中在生成封面时候，会有报错信息：Extra }, or forgotten \endgroup. \makecover。
但是封面是会生成出来。不知道各位有没有遇到类似问题。

**Comment by yifu-wang-201603** [comment]
解决了。
\begin{document}之前加上
\makeatletter
\def\@hspace#1{\begingroup\setlength\skip@{#1}%
    \edef\x{\endgroup\hskip\the\skip@\relax}\x}%
\makeatletter
详情参见
https://github.com/bdebye/thesisuestc/issues/133

**Comment by sierxue** [comment]
谢谢！
